### PR TITLE
User 1 tracklocation

### PR DESCRIPTION
**Pull request by melbrng**
Hi,

Ready for your review!

M

### CODE REVIEW

**Comment by mhanlon** [comment]
This is looking really good right now. I needed to reset my simulator because I had run the main branch first and was logged in as the test user, but the sign up and login flow works well enough right now. One thing we want to clean up is this:
```
2016-07-19 14:14:25.152 Track[53598:4159997] Warning: Attempt to present <UINavigationController: 0x7ffa640de200> on <Track.LoginViewController: 0x7ffa61786a60> whose view is not in the window hierarchy!
```

Let me know if you need any hints or pointers on that one...

**Comment by melbrng** [comment]
I do need a hint :)
Is it because i'm using navigation controllers in the storyboard and since this is the initial VC (not connected to a nav VC) I need to add it to the view hierarchy? And would I do this in the AppDelegate with something like this:

obj-c version....
   self.navigationController = (UINavigationController *)self.window.rootViewController;
   self.photoCollectionViewController = self.navigationController.viewControllers[0];

i've always found this confusing....

**Comment by mhanlon** [comment]
The big issue is how we're presenting it... in a storyboard, you can specify *how* a new view controller is displayed... either push it onto the stack, replace the current view on the stack, present the view as a modal window on the current view (usually for a quick bit of fiddling and then you dismiss that new view), or show the new view controller in a popover...

**Comment by mhanlon** [comment]
untitled

**Comment by mhanlon** [comment]
Which do you think might be the best choice for handling the segue away from the login/signup view controller to our in-use, active view controller... sort of the main purpose view controller of our app?

**Comment by melbrng** [comment]
I would say Show because i'm pushing the map view onto the navigation hierarchy created by using a navigation VC.

**Comment by mhanlon** [comment]
That could be a good one... or replace... It depends if you ever expect to pop back up to the login/signup view controller. But Show would work well.

**Comment by melbrng** [comment]
but if I wanted to be able to pop back to the loginvc (ie logout),  wouldn't I have to add the loginVC onto the navigation stack?

**Comment by melbrng** [comment]
hmmm....apparently I don't :)
I added a logout button to my mapVC and it pops me back to my loginVC

but now i'm receiving this message:

2016-07-19 17:42:58.639 Track[25740:9202193] <UIView: 0x7fc6cc170530; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x7fc6cb493ac0>>'s window is not equal to <UINavigationController: 0x7fc6cd820400>'s view's window!

**Comment by mhanlon** [comment]
That looks excellent. I would probably clear out the username and password when a user logs out, but otherwise, this is about good to go!

**Comment by mhanlon** [comment]
Actually, the other thing we'll want to fix is that error message you mentioned.

So that comes from, typically, loading a view controller multiple times... multiple instances of the view controller on top of one another... This happens a lot when we use segues.

```
        FIRAuth.auth()!.addAuthStateDidChangeListener() { (auth, user) in
            if let user = user {
                print("User is signed in with uid: " + user.uid + " and email: " + user.email!)
                
                //move onto mapview
                self.performSegueWithIdentifier("loginToMap", sender: nil)
                
            } else {
                print("No user is signed in.")
            }
        }
```

If we add a handy bit of code we know will get called each and every time we perform a segue, we see that the above code gets called more than once, which means the `loginToMap` segue is called more than once... Which is where we run into problems.

I'm going to create a quick branch and a pull request so we can compare the differences and see one approach to cleaning up the errors...

**Pull request merged**
